### ISSUE TITLE
[IMPORTERROR] cannot import name 'CeilTimeout' from 'aiohttp.helpers'

### ISSUE THREAD

**Issue by Moham-AT** [haccer/twint#1297]
### Command Ran
import twint
import nest_asyncio
nest_asyncio.apply()
c = twint.Config()
c.Username = "github"

### Description of Issue
its about one month that i am using this repo and it was ok fetching tweets. but today it can't import twint (specifically the aiohttp.helpers and CeilTimeout ) and so i can't fetch any tweet. how can i fix this?

### Environment Details
i'm using twint on google colab and this is the way i use the repo on colab:

!git clone --depth=1 https://github.com/twintproject/twint.git
%cd twint
!git pull origin master
!pip install -r requirements.txt
!python setup.py install

**Comment by akmalsabri** [comment]
yeah I got this issue also

**Comment by usijusolomon** [comment]
Me too

**Comment by chinmaychahar** [comment]
getting the same issue

**Comment by devilliers13** [comment]
Same issue here, fresh install on Ubuntu 20.04 shows the same error. 

ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py

**Comment by mahdi-1992** [comment]
yeah I got this issue also

**Comment by koboskom** [comment]
got same issue, in file /usr/local/lib/python3.7/dist-packages/aiohttp_socks/connector.py comment line 8 "from aiohttp.helpers import CeilTimeout  # noqa", it works fine afterwards

**Comment by josx** [comment]
To fix it you must to have fixed version on aiohttp.
Edit requeriments.txt with  `aiohttp==3.7.0`

**Comment by devilliers13** [comment]
Thanks! that has fixed it.

**Comment by Moham-AT** [comment]
> To fix it you must to have fixed version on aiohttp. Edit requeriments.txt with `aiohttp==3.7.0`

it works, thanks!

**Comment by cihanicelliler** [comment]
> To fix it you must to have fixed version on aiohttp. Edit requeriments.txt with `aiohttp==3.7.0`

It stil didn't change anything. First of all I uninstalled my `aiohttp` then I installed with `aiohttp==3.7.0`  but error didn't change.

**Comment by wjd157** [comment]
Changing aiohttp to aiohttp==3.7.0 in the .txt file did not fix the issue for me either.

**Comment by danielleschn** [comment]
Didn't work for me either, unfortunately.

**Comment by josx** [comment]
@danielleschn @wjd157 @cihanicelliler make sure you did `pip3 install . -r requirements.txt` after changing requirements file from a dependency free environment.  It seems that pip will not downgrade your version if it finds a newer version present.

Or maybe you can do `pip install aiohttp==3.7.0` directly to test it out.

**Comment by abhirup780** [comment]
`pip install aiohttp==3.7.0` directly didn't work. But doing a   `pip3 install . -r requirements.txt` after changing `aiohttp` to `aiohttp==3.7.0` works

**Comment by soukainaElGhaldy** [comment]
Fixed this problem by installing directly aiohttp module on my environment using : `conda install aiohttp ` ! you can use` pip install aiohttp `

**Comment by cracker8090** [comment]
> conda install aiohttp

The version of aiohttp is 3.7.0? my aiohttp is 3.8.1 and errors still exist.

**Comment by danielleschn** [comment]
> Didn't work for me either, unfortunately.

Okay the issue was that I needed to make sure I was installing it in the correct place and then rebuild the docker container, haha.

**Comment by soukainaElGhaldy** [comment]
So Conda environments (also python env) seems to have issues with twint config. So Tried on CLI. what worked for me is what @josx suggested so first I changed `aiohttp` to `aiohttp==3.7.0` in my **requirements.txt** then `pip3 install . -r requirements.txt` and then scrap with for example my `twint -s bitcoin -- since "2021-11-23 11:00:58"` worked fine.
Thank you again @josx  !

**Comment by taohuadaohongye** [comment]
uninstall the aiohttp 3.8 and install aiohttp3.7
command :pip show aiohttp
you will see the aiohttp version is 3.8
command:pip uninstall aiohttp
done,command pip install aiohttp==3.7.0
it will work !

**Comment by Abdelrahmanrezk** [comment]
> To fix it you must to have fixed version on aiohttp. Edit requeriments.txt with `aiohttp==3.7.0`

Thanks for your help,  it solve the problem with me.

**Comment by Icebrey** [comment]
> uninstall the aiohttp 3.8 and install aiohttp3.7 command :pip show aiohttp you will see the aiohttp version is 3.8 command:pip uninstall aiohttp done,command pip install aiohttp==3.7.0 it will work !

thanks mate, it works

**Comment by adamlesniak** [comment]
Hey,

Just tried to run this project and wasn't able to - provided a fix in https://github.com/twintproject/twint/pull/1323 - could be good to have it in `master` for anyone that just tries to use it out of the box.

Thanks,
Adam

**Comment by rehman4u** [comment]
> To fix it you must to have fixed version on aiohttp. Edit requeriments.txt with `aiohttp==3.7.0`

How to edit requirements.txt in aiohttps? Any youtube video on it?

**Comment by adamlesniak** [comment]
> > To fix it you must to have fixed version on aiohttp. Edit requeriments.txt with `aiohttp==3.7.0`
> 
> How to edit requirements.txt in aiohttps? Any youtube video on it?

It's just a file - you can find detailed instructions here:

https://www.jetbrains.com/help/pycharm/managing-dependencies.html#create-requirements

Or you can clone my fork and it covers this update: https://github.com/adamlesniak/twint

**Comment by pragyakarki** [comment]
Thank you @josx . Came across this issue while trying to run twint in Github Actions with latest ubuntu version.

**Comment by RajaKathireshh** [comment]
First install this in a separate cell `pip install aiohttp==3.7.0`
then install `!pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`
now `import twint`
It's working fine for me and I'm able to crawl data.

If still not working, restart the runtime and follow the same order. Sometimes restarting the runtime after installation works.

**Comment by KlausGlueckert** [comment]
same error, chaning to ```aiohttp==3.7.0``` solved it

**Comment by gmusebe** [comment]
> @danielleschn @wjd157 @cihanicelliler make sure you did `pip3 install . -r requirements.txt` after changing requirements file from a dependency free environment. It seems that pip will not downgrade your version if it finds a newer version present.
> 
> Or maybe you can do `pip install aiohttp==3.7.0` directly to test it out.

The last bit fixed it for me
